docs/generator.md
tslib.d.ts
tslib.js

Adds the `__generator` helper that is now in TypeScript/master

Adds __generator helper

---

tslib.es6.js
tslib.js

Port null/undefined support in __rest from https://github.com/Microsoft/TypeScript/pull/12552

---

tslib.es6.js
tslib.js

As per https://github.com/Microsoft/TypeScript/pull/12869 .
cc @mhegazy

Fix IE8 compat in Function.apply calls

---

bower.json
tslib.es6.html
tslib.html

Adding bower support and HTML5 importable modules (#15).

Adding bower support

---

tslib.es6.js
tslib.js

This patches tslib with the helper changes from https://github.com/Microsoft/TypeScript/pull/15241.

Fix yield in async generator

---

tslib.js

set the __esModule marker in createExporter

---

README.md

Made the README a little more explicit about why the package is useful.

---

tslib.d.ts
tslib.es6.js
tslib.js

From [TypeScript #19675](https://github.com/Microsoft/TypeScript/pull/19675)

Add import helpers

---

tslib.es6.js
tslib.js

This updates the `__generator` helper to match the changes in Microsoft/TypeScript#24463.

Update __generators helper to match TS#24463

---

package.json

To match https://github.com/microsoft/TypeScript/blob/7ed3896a0adbcca218470f29081d4af2e8743375/package.json#L4
(you might wanna redirect to https on your site as well)

chore: use https for website

---

tslib.es6.js
tslib.js

this is in relation to https://github.com/microsoft/TypeScript/issues/32458
and https://github.com/microsoft/TypeScript/pull/32468
it fixes also fixes #59

#microsoft/typescript#32458 generators in ie

---

tslib.d.ts

This&nbsp;should’ve been&nbsp;done in&nbsp;#77.
---
review?(@rbuckton)

feat: Add type information to private field helper functions

---

tslib.es6.js
tslib.js

This is for https://github.com/microsoft/TypeScript/pull/38808

Skip default when initially iterating exports in __importStar, same as __exportStar

---

tslib.es6.js
tslib.js

See <https://github.com/microsoft/TypeScript/pull/37013> for explanation.

fix: Use `hasOwnProperty.call`

---

tslib.d.ts
tslib.es6.js
tslib.js

Rename 'exports' argument in '__exportStar' helper

---

README.md

Gives a list to work through, because I missed the bower step last time

Update README.md for deploy docs

---

tslib.d.ts
tslib.es6.js
tslib.js

Further to #160, make license changes to tslib.d.ts, tslib.es6.js and tslib.js files too

Update license within js files

---

tslib.es6.js
tslib.js

See: https://github.com/microsoft/TypeScript/pull/51274

Fix asyncDelegator reporting done too early

---

bower.json
package.json

Bumping package version to prepare for npm publish.

Bump package version to 2.5.0

---

modules/index.d.ts

cc @andrewbranch 
related to https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260

Add proper declaration file for the `import` condition

---

package.json
tslib.es6.js
tslib.js

This is the tslib side of https://github.com/microsoft/TypeScript/pull/54269.

Reverse order of decorator-injected initializers

---

modules/index.d.ts
modules/index.js
tslib.d.ts
tslib.es6.js
tslib.es6.mjs
tslib.js

This adds the helpers from https://github.com/microsoft/TypeScript/pull/54505.

Add helpers for `using` and `await using`

---

tslib.es6.js

Stop using es6 syntax in the es6 file

---

package.json

Fix path to `exports["module"]["types"]`

---

.github/workflows/CI.yml
.github/workflows/codeql.yml
.github/workflows/publish.yaml

CI: set minimal permissions for GitHub Workflows

---

.github/codeql/codeql-configuration.yml
.github/workflows/codeql.yml

I hit the button in the GUI to set this up then copied it into a PR (since the GUI failed to commit it).
This should fix things up; the permissions are the main thing that are broken but the rest is fine.

Update codeql workflow using GUI

---

tslib.es6.js
tslib.es6.mjs
tslib.js

This is the companion PR to https://github.com/microsoft/TypeScript/pull/58929

Implement deterministic collapse of `await` in `await using`

---

tslib.es6.js
tslib.es6.mjs
tslib.js

This is the companion PR to microsoft/TypeScript#59514

Use global 'Iterator.prototype' for downlevel generators

---

tslib.es6.js
tslib.es6.mjs
tslib.js

This is the companion PR to https://github.com/microsoft/TypeScript/pull/60262.

Include non-enumerable keys in __importStar helper
